package clsdl

import "github.com/veandco/go-sdl2/sdl"

const tileSize int32 = 64

var (

	// texturesEnvironment
	textureBackground = [6]sdl.Rect{
		{X: 0 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		{X: 1 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		{X: 2 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		{X: 3 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		{X: 4 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		{X: 5 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
	}

	// texturesEnvironment
	textureObstacles = [6]sdl.Rect{
		{X: 0 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		{X: 1 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		{X: 2 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		{X: 3 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		{X: 4 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		{X: 5 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
	}

	textureRoads = map[string]sdl.Rect{
		"up;down":    {X: 0 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"down;up":    {X: 0 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"left;right": {X: 1 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"right;left": {X: 1 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},

		"up;right":   {X: 0 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"right;up":   {X: 0 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"right;down": {X: 1 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"down;right": {X: 1 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"down;left":  {X: 2 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"left;down":  {X: 2 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"left;up":    {X: 3 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"up;left":    {X: 3 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},

		"start;up":    {X: 0 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"start;right": {X: 1 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"start;down":  {X: 2 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"start;left":  {X: 3 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},

		"up;end":    {X: 0 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"right;end": {X: 1 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"down;end":  {X: 2 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"left;end":  {X: 3 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
	}

	textureTowers = map[string][16]sdl.Rect{
		"Soldier": {
			{X: 0 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 1 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 2 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 3 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 4 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 5 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 6 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 7 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 8 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 9 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 10 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 11 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 12 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 13 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 14 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 15 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		},
		"Sniper": {
			{X: 0 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 1 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 2 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 3 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 4 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 5 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 6 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 7 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 8 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 9 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 10 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 11 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 12 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 13 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 14 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 15 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		},
		"Scout": {
			{X: 0 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 1 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 2 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 3 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 4 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 5 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 6 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 7 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 8 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 9 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 10 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 11 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 12 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 13 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 14 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 15 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		},
		"Heavy": {
			{X: 0 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 1 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 2 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 3 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 4 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 5 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 6 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 7 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 8 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 9 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 10 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 11 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 12 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 13 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 14 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
			{X: 15 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		},
	}

	textureEnemies = map[string]sdl.Rect{
		"up;down":    {X: 0 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"right;left": {X: 2 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"down;up":    {X: 4 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"left;right": {X: 6 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},

		"right;down": {X: 1 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"up;left":    {X: 1 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"right;up":   {X: 3 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"down;left":  {X: 3 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"down;right": {X: 5 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"left;up":    {X: 5 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"up;right":   {X: 7 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"left;down":  {X: 7 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},

		"start;down":  {X: 0 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"start;left":  {X: 2 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"start;up":    {X: 4 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"start;right": {X: 6 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},

		"up;end":    {X: 0 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"right;end": {X: 2 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"down;end":  {X: 4 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"left;end":  {X: 6 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
	}

	textureText = map[rune]sdl.Rect{
		' ': {X: -1 * tileSize, Y: -1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},

		'�': {X: 0 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},

		'0': {X: 1 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'1': {X: 2 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'2': {X: 3 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'3': {X: 4 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'4': {X: 5 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'5': {X: 6 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'6': {X: 7 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'7': {X: 8 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'8': {X: 9 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'9': {X: 10 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},

		'a': {X: 0 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'b': {X: 1 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'c': {X: 2 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'd': {X: 3 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'e': {X: 4 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'f': {X: 5 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'g': {X: 6 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'h': {X: 7 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'i': {X: 8 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'j': {X: 9 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'k': {X: 10 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'l': {X: 11 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'm': {X: 12 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'n': {X: 13 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'o': {X: 14 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'p': {X: 15 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'q': {X: 16 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'r': {X: 17 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		's': {X: 18 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		't': {X: 19 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'u': {X: 20 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'v': {X: 21 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'w': {X: 22 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'x': {X: 23 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'y': {X: 24 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'z': {X: 25 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},

		'A': {X: 0 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'B': {X: 1 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'C': {X: 2 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'D': {X: 3 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'E': {X: 4 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'F': {X: 5 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'G': {X: 6 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'H': {X: 7 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'I': {X: 8 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'J': {X: 9 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'K': {X: 10 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'L': {X: 11 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'M': {X: 12 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'N': {X: 13 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'O': {X: 14 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'P': {X: 15 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'Q': {X: 16 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'R': {X: 17 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'S': {X: 18 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'T': {X: 19 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'U': {X: 20 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'V': {X: 21 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'W': {X: 22 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'X': {X: 23 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'Y': {X: 24 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'Z': {X: 25 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},

		'!':  {X: 0 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'?':  {X: 1 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'"':  {X: 2 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'#':  {X: 3 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'$':  {X: 4 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'%':  {X: 5 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'&':  {X: 6 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'\'': {X: 7 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'(':  {X: 8 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		')':  {X: 9 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'*':  {X: 10 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'+':  {X: 11 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		',':  {X: 12 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'-':  {X: 13 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'.':  {X: 14 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'/':  {X: 15 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		':':  {X: 16 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		';':  {X: 17 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'<':  {X: 18 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'=':  {X: 19 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'>':  {X: 20 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'@':  {X: 21 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'[':  {X: 22 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'\\': {X: 23 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		']':  {X: 24 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'^':  {X: 25 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'_':  {X: 26 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'`':  {X: 27 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'{':  {X: 28 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'|':  {X: 29 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'}':  {X: 30 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		'~':  {X: 31 * tileSize, Y: 3 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
	}

	textureUI = map[string]sdl.Rect{
		"crosshair": {X: 0 * tileSize, Y: 0 * tileSize, W: 1 * tileSize, H: 1 * tileSize},

		"barred;0": {X: 0 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barred;1": {X: 1 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barred;2": {X: 2 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barred;3": {X: 3 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barred;4": {X: 4 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barred;5": {X: 5 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barred;6": {X: 6 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barred;7": {X: 7 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barred;8": {X: 8 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barred;9": {X: 9 * tileSize, Y: 1 * tileSize, W: 1 * tileSize, H: 1 * tileSize},

		"barblue;0": {X: 0 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barblue;1": {X: 1 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barblue;2": {X: 2 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barblue;3": {X: 3 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barblue;4": {X: 4 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barblue;5": {X: 5 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barblue;6": {X: 6 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barblue;7": {X: 7 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barblue;8": {X: 8 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
		"barblue;9": {X: 9 * tileSize, Y: 2 * tileSize, W: 1 * tileSize, H: 1 * tileSize},
	}
)
